CREATE TABLE IF NOT EXISTS orders (
    oid      SERIAL PRIMARY KEY,
    cid      SERIAL NOT NULL REFERENCES customers(cid) ON DELETE CASCADE,
    ts       TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_oid ON orders (oid);

